import type { LearningPath } from "./types";

/**
 * 学习路径 — 有序课程序列，可跨模块。
 * lessonId 必须与管线生成的课程 id 一致（构建时校验）。
 */
export const LEARNING_PATHS: LearningPath[] = [
  {
    id: "foundation",
    title: "K8s 基础主线",
    description:
      "从零搭建一套生产级 Kubernetes 集群：规划、部署、网络、存储接入与基础观测，对应参考库根目录的推荐学习顺序。",
    lessonIds: [
      "k8s",
      "os/os",
      "k8s/plan",
      "k8s/etcd-disk-performance",
      "k8s/os",
      "k8s/kubespray",
      "k8s/client",
      "k8s/sa-management",
      "base",
      "base/nfd",
      "base/spegel",
      "base/kube-node-tuning",
      "network",
      "network/cilium",
      "network/metallb",
      "network/istio/ingress",
      "network/cert-manager",
      "storage",
      "storage/local-storage",
      "storage/volumesnapshots",
      "o11y/vm",
    ],
  },
  {
    id: "ceph-series",
    title: "Ceph 存储实战",
    description: "使用 Cephadm 从零部署 Ceph 集群，提供 RADOS / CephFS / RBD / RGW 全栈存储服务并接入 CSI。",
    lessonIds: [
      "storage/cephadm",
      "storage/cephadm/1-deploy-ceph-cluster",
      "storage/cephadm/2-ceph-rados",
      "storage/cephadm/3-deploy-cephfs",
      "storage/cephadm/4-deploy-rbd",
      "storage/cephadm/5-deploy-rgw",
      "storage/cephadm/6-add-custom-rgw-exporter",
      "storage/cephadm/7-faq",
      "storage/cephadm/8-metrics",
      "storage/cephadm/day-2",
      "storage/ceph-csi-cephfs",
      "storage/ceph-csi-rbd",
      "storage/ceph-snapshot",
    ],
  },
  {
    id: "gpfs-series",
    title: "GPFS / ECE 存储实战",
    description: "GPFS（Spectrum Scale / ECE）的 day 0 规划到 day 2 运维全生命周期：概念、网络、纠删码集群、部署与调优。",
    lessonIds: [
      "storage/gpfs",
      "storage/gpfs/day-0-concept",
      "storage/gpfs/day-0-network",
      "storage/gpfs/day-0-plan-ece",
      "storage/gpfs/day-1-deploy-ece",
      "storage/gpfs/day-1-deploy-dme",
      "storage/gpfs/day-1-tunning",
      "storage/gpfs/day-2-management",
      "storage/gpfs/day-2-scaling-cluster",
      "storage/gpfs/day-2-snapshot",
      "storage/gpfs-csi",
    ],
  },
  {
    id: "ai-platform",
    title: "AI 平台建设",
    description: "GPU 资源管理、批处理调度选型（Kueue / Volcano）、分布式训练与 LLM 推理服务的完整落地路线。",
    lessonIds: [
      "ai",
      "ai/gpu-operator",
      "ai/scheduling-comparison",
      "ai/kueue",
      "ai/volcano",
      "ai/trainer",
      "ai/trainer/examples/pytorch-megatron",
      "ai/nccl-tests/quickstart",
      "ai/lws",
      "ai/llm",
    ],
  },
  {
    id: "observability",
    title: "可观测性",
    description: "以 VictoriaMetrics 为核心的指标体系，配合 Loki / VictoriaLogs 日志与 K8s 事件采集。",
    lessonIds: [
      "o11y",
      "o11y/vm",
      "o11y/logs",
      "o11y/logs/loki",
      "o11y/logs/vl",
      "o11y/logs/collectors/kubernetes-event-exporter",
    ],
  },
  {
    id: "registry-mirrors",
    title: "镜像仓库与加速",
    description: "容器镜像仓库（Registry / Harbor）搭建、P2P 分发加速与 PyPI / Conda 科学计算镜像源。",
    lessonIds: [
      "repo",
      "repo/registry",
      "repo/harbor",
      "repo/dragonfly",
      "repo/pypi",
      "repo/conda",
    ],
  },
  {
    id: "databases",
    title: "数据库上 K8s",
    description: "Redis 单机部署、KubeBlocks 数据库管理平台 day 0-3 实战，以及 TiKV 集群的运维手册。",
    lessonIds: [
      "db",
      "db/redis",
      "db/kubeblocks",
      "db/kubeblocks/kbcli-0.9.3/day-0-kubeblocks",
      "db/kubeblocks/kbcli-0.9.3/day-1-mysql",
      "db/kubeblocks/kbcli-0.9.3/day-2-postgresql",
      "db/kubeblocks/kbcli-0.9.3/day-3-redis",
      "db/tikv/deployment",
      "db/tikv/scale-cluster",
      "db/tikv/backup-restore",
    ],
  },
  {
    id: "virtualization",
    title: "虚拟化与多租户",
    description: "vCluster 虚拟集群、Kamaji 托管控制面与 KubeVirt 虚拟机，在共享集群上实现租户隔离。",
    lessonIds: [
      "compute",
      "compute/vcluster",
      "compute/vcluster/vcluster-demo",
      "compute/kamaji",
      "compute/kamaji/examples/mycluster/join-worker-nodes",
      "compute/kubevirt/workload",
    ],
  },
];
